spring:
  config:
    activate:
      on-profile: dev

location:
  target-url:
    #member: http://api-member.default.svc.cluster.local:18081
    member: http://localhost:18081
    #board: http://api-board.default.svc.cluster.local:18082
    board: http://localhost:18082
