server:
  port: 18080
  error:
    include-message: always

logging:
  level:
    root: info

spring:
  profiles:
    default: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
